name: Angular Build, Test, and Deploy to SFTP Server

on:
  push:
    branches:
      - main

env:
  SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
  SFTP_PORT: ${{ secrets.SFTP_PORT }}
  SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
  SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
  SFTP_LOCAL_PATH: ${{ secrets.SFTP_LOCAL_PATH }}
  SFTP_REMOTE_PATH: ${{ secrets.SFTP_REMOTE_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build and test Angular project
        run: |
          npm run build
#          npm run test

      - name: Deploy to SFTP server
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ env.SFTP_SERVER }}
          port: ${{ env.SFTP_PORT }}
          username: ${{ env.SFTP_USERNAME }}
          password: ${{ env.SFTP_PASSWORD }}
          localPath: ${{ env.SFTP_LOCAL_PATH }}
          remotePath: ${{ env.SFTP_REMOTE_PATH }}


